define Display
	@echo "Entry Point "
	@echo "0 is $0"
	@echo "1 is $1"
	@echo "2 is $2"
	@echo "Target is $@"
	@echo "Exit Point"
endef

x := Magid
target:
	$(call Display , Muhammed,$(x))

target2: 
	@echo $(wildcard *.cpp)
